# Generated by Django 5.0.3 on 2024-04-11 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pc_builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="motherboard",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pc_builder.brand",
            ),
        ),
    ]
