# Generated by Django 5.0.4 on 2024-04-15 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pc_builder", "0005_rename_processor_configuration_cpu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CpuCooler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "manufacturer",
                    models.CharField(
                        choices=[
                            ("intel", "Intel"),
                            ("amd", "AMD"),
                            ("nvidia", "Nvidia"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("msrp_price", models.FloatField()),
                (
                    "image",
                    models.ImageField(
                        default="default.jpg",
                        null=True,
                        upload_to="static/images/components/",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pc_builder.brand",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
