# Generated by Django 5.0.4 on 2024-04-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pc_builder", "0008_case_brand_case_image_case_manufacturer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="msrp_price",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="case",
            name="manufacturer",
            field=models.CharField(
                choices=[
                    ("intel", "Intel"),
                    ("amd", "AMD"),
                    ("nvidia", "Nvidia"),
                    ("none", "None"),
                ],
                default="None",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cpucooler",
            name="manufacturer",
            field=models.CharField(
                choices=[
                    ("intel", "Intel"),
                    ("amd", "AMD"),
                    ("nvidia", "Nvidia"),
                    ("none", "None"),
                ],
                default="None",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gpu",
            name="manufacturer",
            field=models.CharField(
                choices=[
                    ("intel", "Intel"),
                    ("amd", "AMD"),
                    ("nvidia", "Nvidia"),
                    ("none", "None"),
                ],
                default="None",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="motherboard",
            name="manufacturer",
            field=models.CharField(
                choices=[
                    ("intel", "Intel"),
                    ("amd", "AMD"),
                    ("nvidia", "Nvidia"),
                    ("none", "None"),
                ],
                default="None",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="powersupply",
            name="manufacturer",
            field=models.CharField(
                choices=[
                    ("intel", "Intel"),
                    ("amd", "AMD"),
                    ("nvidia", "Nvidia"),
                    ("none", "None"),
                ],
                default="None",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="processor",
            name="manufacturer",
            field=models.CharField(
                choices=[
                    ("intel", "Intel"),
                    ("amd", "AMD"),
                    ("nvidia", "Nvidia"),
                    ("none", "None"),
                ],
                default="None",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ram",
            name="manufacturer",
            field=models.CharField(
                choices=[
                    ("intel", "Intel"),
                    ("amd", "AMD"),
                    ("nvidia", "Nvidia"),
                    ("none", "None"),
                ],
                default="None",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="manufacturer",
            field=models.CharField(
                choices=[
                    ("intel", "Intel"),
                    ("amd", "AMD"),
                    ("nvidia", "Nvidia"),
                    ("none", "None"),
                ],
                default="None",
                max_length=6,
                null=True,
            ),
        ),
    ]
