# Generated by Django 5.0.3 on 2024-04-10 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_created_by_postcomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-date_posted"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_by",
            new_name="author",
        ),
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog.posttopic",
            ),
        ),
    ]
